# KHistoryQuiz 플러그인 설정
# question-set-filter: questions.yml의 문제들 중 특정 범위 또는 특정 문제들을 제외합니다.
# 예시: (문제들의 번호를 사용, 필터링을 하지 않는 경우 값을 none으로 입력)
question-set-filter: none

# interval: 게임 내에서 플러그인을 시작한 경우 문제가 나오는 시간 간격을 변경
# 'random' 또는 ms 단위의 시간 단위로 입력, random일 경우 플러그인이 4분(240000)마다 문제를 표시합니다.
# 1초 = 1000ms(밀리초)
interval: 240000

# question-timeout: 각 문제가 표시되는 시간을 초 단위로 설정합니다.
# 기본값: 10초
question-timeout: 10